name: 'GPT Engineer'
description: 'An AI engineer scans your codebase and edits the files based on the goals you provide it.'
inputs:
  repository_url:
    description: 'The repository url to scan and make edits in.'
    required: true
  base_branch:
    description: 'The base branch to base the edits on.'
    required: true
  dev_branch:
    description: 'The dev branch to edit.'
    required: true
  path:
    description: 'The path to scan and make edits in.'
    required: true
  goal:
    description: 'The goal to achieve.'
    required: true
outputs:
  status:
    description: 'The status of the action.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository_url }}
    - ${{ inputs.base_branch }}
    - ${{ inputs.dev_branch }}
    - ${{ inputs.path }}
    - ${{ inputs.goal }}
