on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'The base branch to base the edits on.'
        required: true
        default: 'mainline'
        type: branch
      dev_branch:
        description: 'The development branch to make the edits on.'
        required: true
        default: 'gpt-eng'
      path:
        description: 'The path to scan and make edits in.'
        required: true
      goal:
        description: 'The goal to achieve.'
        required: true

jobs:
  gpt_engineer:
    runs-on: ubuntu-latest
    name: GPT Engineer
    steps:
      - name: Start the engineering task
        id: gpt
        uses: ncrews35/gpt-engineer@mainline
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
          BOT_NAME: 'Bulsai'
          BOT_EMAIL: 'bot@buls.ai'
        with:
          args: ${{ inputs.base_branch }} ${{ inputs.dev_branch }} ${{ inputs.path }} ${{ inputs.goal }}
        working_directory: ${{ github.workspace }}
